# inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - bin/htmldiff
    - bin/ldiff
    - bin/rspec
Style/BlockComments:
  Enabled: false
Naming/MethodName:
  EnforcedStyle: camelCase
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
